services:
  #templating
  Mayordomo\Infrastructure\Engine\Templating:
    class: Mayordomo\Infrastructure\Engine\Templating
    public: true

  #routing
  Mayordomo\Infrastructure\Routing\Router:
    class: Mayordomo\Infrastructure\Routing\Router
    arguments: ['@service_container']
    public: true

  #controllers
  Mayordomo\Ui\Controller\HomePageController:
    class: Mayordomo\Ui\Controller\HomePageController
    arguments: ['@service_container']
    public: true

  Mayordomo\Ui\Controller\ApiController:
    class: Mayordomo\Ui\Controller\ApiController
    arguments: ['@service_container']
    public: true
